[theme]
base = "dark"
primaryColor = "#E69984"
backgroundColor = "#0D1110"
secondaryBackgroundColor = "#1A231F"
textColor = "#E8E4DC"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
